version: '3.3'
services:

  # sftpd server that accepts debian source packages
  sftpd-deb-src:
    build:
      context: ./sftpd
      dockerfile: ./Dockerfile
    image: sftpd-mlp
    ports:
      - "8022:22"
    volumes:
      - sftpd-deb-src-incoming:/home/myuser/incoming
      - ./sftpd/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./sftpd/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    command: myuser:pass

  # mini-launchpad consumes a debian source package and produces
  # a debian binary package
  mini-launchpad:
    build:
      context: ../
      dockerfile: ./docker/mini-launchpad/Dockerfile
    privileged: true
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - sftpd-deb-src
    volumes:
      - sftpd-deb-src-incoming:/root/incoming
      - pbuilder-cache:/var/cache/pbuilder
      - wwwroot-mini-launchpad:/root/build-logs
      - ./sftpd-bin/ssh_host_rsa_key:/root/.ssh/id_rsa:ro
      - ./mini-launchpad/known_hosts:/root/.ssh/known_hosts
  
  # This web server hosts the mini-launchpad build logs
  mini-launchpad-web:
    image: httpd
    ports:
      - "9080:80"
    depends_on:
      - mini-launchpad
    volumes:
      - wwwroot-mini-launchpad:/usr/local/apache2/htdocs/build-logs

  # sftpd server that accepts debian binary packages from mini-launchpad
  sftpd-deb-bin:
    image: sftpd-mlp
    ports:
      - "8023:22"
    volumes:
      - sftpd-deb-bin-incoming:/home/myuser/incoming
      - ./sftpd-bin/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./sftpd-bin/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ./sftpd-bin/ssh_host_rsa_key.pub:/home/myuser/.ssh/keys/id_rsa.pub:ro
    command: myuser:pass
  
  # reprepro consumes a debian binary package and puts it in a valid
  # debian repository
  reprepro:
    build:
      context: ./reprepro
      dockerfile: ./Dockerfile
    image: mlp/reprepro
    depends_on:
      - sftpd-deb-bin
    environment:
      DISTRIBUTION: "xenial bionic"
      NO_CHANGES_FILE_FLAG: ""
      ALLOW_SAME_VERSION_FLAG: "--allow-same-version"
      PYTHONUNBUFFERED: 1
    volumes:
      - sftpd-deb-bin-incoming:/root/incoming
      - wwwroot-reprepro:/var/repositories
      - ./reprepro/conf:/var/repositories/conf
  
  # This web server hosts the debian binary repository that is generated
  # by reprepro
  reprepro-web:
    image: httpd
    depends_on:
      - reprepro
    ports:
      - "80:80"
    volumes:
      - wwwroot-reprepro:/usr/local/apache2/htdocs/archive

volumes:
  sftpd-deb-src-incoming:
  wwwroot-mini-launchpad:
  sftpd-deb-bin-incoming:
  pbuilder-cache:
  wwwroot-reprepro:
