version: '3.3'
services:

  # ftpd server that accepts debian source packages
  ftpd-deb-src:
    build: pure-ftpd
    image: mlp/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "${PUBLICHOST}"
      PORT_RANGE: "30000:30009"
      ADDED_FLAGS: "--verboselog"
    volumes:
      - ftpd-deb-src-incoming:/home/ftp

  # mini-launchpad consumes a debian source package and produces
  # a debian binary package
  mini-launchpad:
    build:
      context: ../
      dockerfile: ./docker/mini-launchpad/Dockerfile
    privileged: true
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - ftpd-deb-src
    volumes:
      - ftpd-deb-src-incoming:/root/incoming
      - pbuilder-cache:/var/cache/pbuilder
      - wwwroot-mini-launchpad:/root/build-logs

  # This web server hosts the mini-launchpad build logs
  mini-launchpad-web:
    image: httpd
    ports:
      - "9080:80"
    depends_on:
      - mini-launchpad
    volumes:
      - wwwroot-mini-launchpad:/usr/local/apache2/htdocs/build-logs

  # ftpd server that accepts debian binary packages from mini-launchpad
  ftpd-deb-bin:
    build: pure-ftpd
    ports:
      - "8021:21"
      - "40000-40009:40000-40009"
    environment:
      PUBLICHOST: "${PUBLICHOST}"
      PORT_RANGE: "40000:40009"
      ADDED_FLAGS: "--verboselog"
    volumes:
      - ftpd-deb-bin-incoming:/home/ftp

  # reprepro consumes a debian binary package and puts it in a valid
  # debian repository
  reprepro:
    build:
      context: ./reprepro
      dockerfile: ./Dockerfile
    image: mlp/reprepro
    depends_on:
      - ftpd-deb-bin
    environment:
      DISTRIBUTION: "xenial"
      NO_CHANGES_FILE_FLAG: ""
      ALLOW_SAME_VERSION_FLAG: "--allow-same-version"
      PYTHONUNBUFFERED: 1
    volumes:
      - ftpd-deb-bin-incoming:/root/incoming
      - wwwroot-reprepro:/var/repositories
      - ./reprepro/conf:/var/repositories/conf

  # This web server hosts the debian binary repository that is generated
  # by reprepro
  reprepro-web:
    image: httpd
    depends_on:
      - reprepro
    ports:
      - "80:80"
    volumes:
      - wwwroot-reprepro:/usr/local/apache2/htdocs/archive

volumes:
  ftpd-deb-src-incoming:
  wwwroot-mini-launchpad:
  ftpd-deb-bin-incoming:
  pbuilder-cache:
  wwwroot-reprepro:
