version: '3.3'
services:

  # Serves the apt-get repo to other users
  mini-dinstall:
    build: mini-dinstall
    volumes:
      - wwwroot-mini-dinstall:/root/htdocs
    ports:
      - "8021:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "127.0.0.1"
      ADDED_FLAGS: "--verboselog"

  mini-dinstall-web:
    image: httpd
    volumes:
      - wwwroot-mini-dinstall:/usr/local/apache2/htdocs
    ports:
      - "80:80"

  mini-launchpad:
    build: mini-launchpad
    privileged: true
    volumes:
      - pbuilder-cache:/var/cache/pbuilder

volumes:
  wwwroot-mini-dinstall:
  pbuilder-cache:
