version: '3.3'
services:

  pure-ftpd-1:
    build: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "localhost"
      LISTEN_PORT: "21"
      PORT_RANGE: "30000:30009"
      ADDED_FLAGS: "--verboselog"
    volumes:
      - ftp-incoming-1:/home/ftp

  mini-launchpad:
    build:
      context: ../
      dockerfile: ./docker/mini-launchpad/Dockerfile
    privileged: true
    volumes:
      - ftp-incoming-1:/root/incoming
      - pbuilder-cache:/var/cache/pbuilder
      - wwwroot-mini-launchpad:/root/build-logs

  mini-launchpad-web:
    image: httpd
    ports:
      - "9080:80"
    volumes:
      - wwwroot-mini-launchpad:/usr/local/apache2/htdocs/build-logs

  pure-ftpd-2:
    build: pure-ftpd
    ports:
      - "8021:8021"
      - "40000-40009:40000-40009"
    environment:
      PUBLICHOST: "localhost"
      LISTEN_PORT: "8021"
      PORT_RANGE: "40000:40009"
      ADDED_FLAGS: "--verboselog"
    volumes:
      - ftp-incoming-2:/home/ftp

  mini-dinstall:
    build:
        context: ./mini-dinstall
        dockerfile: ./Dockerfile
    volumes:
      - ftp-incoming-2:/root/archive/mini-dinstall/incoming
      - wwwroot-mini-dinstall:/root/archive
      
  mini-dinstall-web:
    image: httpd
    ports:
      - "80:80"
    volumes:
      - wwwroot-mini-dinstall:/usr/local/apache2/htdocs/archive
    
volumes:
  ftp-incoming-1:
  wwwroot-mini-launchpad:
  ftp-incoming-2:
  wwwroot-mini-dinstall:
  pbuilder-cache:
